index:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /calculate
        permanent: true

calculate:
    path: /calculate
    controller: App\Controller\Calculator::calculate
